name: pdf_viewer
description: Abra arquivos PDF com o seu celular

publish_to: 'none' 

version: 0.2.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.2
  permission_handler: ^10.2.0
  syncfusion_flutter_pdfviewer: ^20.4.49
  file_picker: ^5.2.5
  share_extend: ^2.0.0
  localstorage: ^4.0.0+1
  flutter_svg: ^2.0.0+1
  printing: ^5.10.1

dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images
    - assets/images/logo/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
